name: CI hello
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  CI:
    name: Publish hello app
    runs-on: ubuntu-latest
    steps:
- name: Call Dagger Publish Function
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          module: github.com/shykes/daggerverse/hello@v0.1.2
          args: publish --source=.
          # assumes the Dagger Cloud token is in
          # a repository secret named DAGGER_CLOUD_TOKEN
          # set via the GitHub UI/CLI
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
